services:

  db:
    image: mongo:8.3.1
    container_name: portfolio-mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - portfolio-network

  backend:
    depends_on: 
      - db
    image: portfolio-backend:latest  # ← image du registry, plus de build
    container_name: portfolio-backend
    restart: unless-stopped
    environment:
      - MONGO_URI=${MONGO_URI}
      - CORS_ORIGIN=${CORS_ORIGIN}
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
      - CORS_ORIGIN=${CORS_ORIGIN}
    networks:
      - portfolio-network

  frontend:
    depends_on: 
      - backend
    image: portfolio-frontend:latest  # ← image du registry, plus de build
    container_name: portfolio-frontend
    restart: unless-stopped
    container_name: portfolio-frontend
    ports:
      - "8000:80"
    networks:
      - portfolio-network

volumes:
  mongo-data:

networks:
  portfolio-network:

