apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    io.kompose.service: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      labels:
        io.kompose.service: backend
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: worker-2
      imagePullSecrets:
        - name: docker-hub-secret
      containers:
        - name: portfolio-server
          image: ${DOCKER_HUB_USER}/portfolio-server:latest
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CORS_ORIGIN
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
          readinessProbe:           # attendre que le backend soit prêt
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
      restartPolicy: Always