apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    io.kompose.service: db
spec:
  type: ClusterIP        # interne uniquement, pas besoin d'exposer MongoDB
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: db