apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  labels:
    io.kompose.service: mongo-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi        # 100Mi trop petit pour MongoDB, minimum 1Gi