apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    io.kompose.service: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      labels:
        io.kompose.service: frontend
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: worker-2
      imagePullSecrets:
        - name: docker-hub-secret
      containers:
        - name: portfolio-app
          image: ${DOCKER_HUB_USER}/portfolio-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          # VITE_API_URL est injecté au build, pas au runtime
          # Elle est déjà compilée dans le bundle par Docker build
      restartPolicy: Always